from __future__ import annotations

from pathlib import Path
from types import SimpleNamespace

import cv2
import numpy as np
import pytest

from bim_priorda3.config import Config
from bim_priorda3.data.preparation import (
    DA3_CACHE_SCHEMA_VERSION,
    DA3PredictionProvider,
)


def _config(cache: Path) -> Config:
    return Config(
        data=Config(
            da3_cache_roots={},
            da3_model="depth-anything/test-model",
            da3_revision="0123456789abcdef",
            local_files_only=True,
            da3_require_pinned_revision=True,
            da3_process_res=8,
        ),
        project_root=str(cache.parent),
    )


def _image(path: Path, value: int = 127) -> None:
    assert cv2.imwrite(str(path), np.full((8, 8, 3), value, dtype=np.uint8))


def test_legacy_cache_requires_explicit_attested_finalization(tmp_path: Path) -> None:
    image = tmp_path / "frame.png"
    _image(image)
    cache = tmp_path / "cache"
    cache.mkdir()
    cache_path = cache / "frame.npz"
    depth = np.full((8, 8), 2.0, dtype=np.float16)
    confidence = np.full((8, 8), 0.75, dtype=np.float16)
    np.savez_compressed(cache_path, depth=depth, confidence=confidence)
    provider = DA3PredictionProvider(_config(cache), "area_1", cache)

    with pytest.raises(ValueError, match="finalize-legacy"):
        provider.get_with_provenance(image, (8, 8))

    inspection = provider.inspect_legacy_cache(image, (8, 8))
    migrated = provider.finalize_legacy_cache(
        image,
        (8, 8),
        generation_attestation="Generated by the pinned model before schema-v2 rollout.",
        inspection=inspection,
    )
    assert migrated["status"] == "migrated_legacy"
    assert migrated["original_sha256"] != migrated["final_sha256"]

    prediction = provider.get_with_provenance(image, (8, 8))
    assert prediction.provenance_status == "legacy_user_attested"
    assert prediction.model_revision == "0123456789abcdef"
    np.testing.assert_array_equal(prediction.depth, depth.astype(np.float32))
    with np.load(cache_path, allow_pickle=False) as item:
        assert int(item["schema_version"]) == DA3_CACHE_SCHEMA_VERSION
        assert str(item["legacy_generation_attestation"].item()).startswith("Generated")


def test_cache_is_bound_to_exact_image_and_target_shape(tmp_path: Path) -> None:
    image = tmp_path / "frame.png"
    _image(image)
    cache = tmp_path / "cache"
    cache.mkdir()
    np.savez_compressed(
        cache / "frame.npz",
        depth=np.ones((8, 8), dtype=np.float16),
        confidence=np.ones((8, 8), dtype=np.float16),
    )
    provider = DA3PredictionProvider(_config(cache), "area_1", cache)
    provider.finalize_legacy_cache(
        image,
        (8, 8),
        generation_attestation="Explicit test attestation",
    )

    with pytest.raises(ValueError, match="target_shape"):
        provider.get_with_provenance(image, (4, 4))
    _image(image, value=20)
    with pytest.raises(ValueError, match="image_sha256"):
        provider.get_with_provenance(image, (8, 8))


def test_new_inference_is_pinned_and_written_as_valid_schema(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    image = tmp_path / "new.png"
    _image(image)
    cache = tmp_path / "cache"
    calls: dict[str, object] = {}

    class FakeModel:
        _commit_hash = "0123456789abcdef"

        @classmethod
        def from_pretrained(cls, name: str, **kwargs: object) -> FakeModel:
            calls["name"] = name
            calls.update(kwargs)
            return cls()

        def to(self, device: object) -> FakeModel:
            calls["device"] = device
            return self

        def eval(self) -> FakeModel:
            return self

        def inference(self, *_args: object, **kwargs: object) -> SimpleNamespace:
            calls["inference"] = kwargs
            return SimpleNamespace(
                depth=np.full((1, 4, 4), 1.5, dtype=np.float32),
                conf=np.full((1, 4, 4), 0.5, dtype=np.float32),
            )

    import depth_anything_3.api

    monkeypatch.setattr(depth_anything_3.api, "DepthAnything3", FakeModel)
    provider = DA3PredictionProvider(_config(cache), "area_1", cache)
    prediction = provider.get_with_provenance(image, (8, 8))

    assert calls["name"] == "depth-anything/test-model"
    assert calls["revision"] == "0123456789abcdef"
    assert calls["local_files_only"] is True
    assert prediction.provenance_status == "direct_inference"
    assert prediction.cache_path.is_file()
    assert not list(cache.glob("*.tmp"))
